theme: jekyll-theme-cayman
title: GoXTree
description: Gerenciador de arquivos moderno inspirado no XTree Gold
show_downloads: true
google_analytics:
github:
  zip_url: https://github.com/peder1981/GoXTree/archive/v1.0.0.zip
  tar_url: https://github.com/peder1981/GoXTree/archive/v1.0.0.tar.gz
  repository_url: https://github.com/peder1981/GoXTree
